/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpm.assi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author yasho
 */
public class des14 extends javax.swing.JFrame {
    
 Connection con;         //create the connection object con
 PreparedStatement pst; // create the PreparedStatement object pst
 ResultSet rs;          // create the ResultSet object rs
 Statement stmt;        // create the Statement object stmt


    
    public des14() {
        initComponents();
        DisplayTable();
    }
        
         private void DisplayTable(){
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmproject?zeroDateTimeBehavior=convertToNull", "root",""); 
            
            String sql = "select * from time_slot"; 
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery(sql);
            
            while(rs.next()){
                
                 String id = String.valueOf(rs.getInt("id"));
                 String selected_day = rs.getString("selected_day");
                 String time_slot = rs.getString("time_slot");
                 String starting_time = rs.getString("starting_time");
                 
                 String tbData[] = {id,selected_day,time_slot,starting_time};
                 DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel(); 
                 
                 tblModel.addRow(tbData);
                
            }
      
        }catch(Exception e){
            
           JOptionPane.showMessageDialog(null, e); 
        
        }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tslotupdatebtn = new javax.swing.JButton();
        tslotdelbtn = new javax.swing.JButton();
        timeslotsave2 = new javax.swing.JButton();
        dayselectbtn2 = new javax.swing.JComboBox<String>();
        hrbtn2 = new javax.swing.JRadioButton();
        minbtn2 = new javax.swing.JRadioButton();
        sday2 = new javax.swing.JLabel();
        stime2 = new javax.swing.JLabel();
        sts2 = new javax.swing.JLabel();
        stime3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Time Slots");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269)
                .addComponent(jLabel6)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Day", "Time slot", "Starting time"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tslotupdatebtn.setBackground(new java.awt.Color(106, 116, 145));
        tslotupdatebtn.setForeground(new java.awt.Color(255, 255, 255));
        tslotupdatebtn.setText("Update");
        tslotupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tslotupdatebtnActionPerformed(evt);
            }
        });

        tslotdelbtn.setBackground(new java.awt.Color(106, 116, 145));
        tslotdelbtn.setForeground(new java.awt.Color(255, 255, 255));
        tslotdelbtn.setText("Delete");
        tslotdelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tslotdelbtnActionPerformed(evt);
            }
        });

        timeslotsave2.setBackground(new java.awt.Color(106, 116, 145));
        timeslotsave2.setForeground(new java.awt.Color(255, 255, 255));
        timeslotsave2.setText("Clear All");
        timeslotsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeslotsave2ActionPerformed(evt);
            }
        });

        dayselectbtn2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        dayselectbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayselectbtn2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(hrbtn2);
        hrbtn2.setText("hour");
        hrbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrbtn2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(minbtn2);
        minbtn2.setText("min");
        minbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minbtn2ActionPerformed(evt);
            }
        });

        sday2.setText("Select day :");

        stime2.setText("Starting time :");

        sts2.setText("Select time slot :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeslotsave2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tslotdelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tslotupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stime2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sts2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hrbtn2)
                                        .addGap(70, 70, 70))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(stime3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sday2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dayselectbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(minbtn2)))))
                        .addGap(36, 36, 36)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tslotupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayselectbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sday2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tslotdelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sts2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minbtn2)
                        .addComponent(hrbtn2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeslotsave2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stime2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stime3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tslotupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tslotupdatebtnActionPerformed
        // TODO add your handling code here:
 
        try{
             Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmproject?zeroDateTimeBehavior=convertToNull", "root",""); 
             int row = jTable1.getSelectedRow();
             String value = (jTable1.getModel().getValueAt(row, 0).toString());
             String sql = "UPDATE time_slot SET selected_day=?, time_slot=?, starting_time=? WHERE id ="+value;
             pst = con.prepareStatement(sql);
            
            
            String selected_day;
            selected_day = dayselectbtn2.getSelectedItem().toString();
            pst.setString(1, selected_day);
            
            String time_slot = "";
            if(hrbtn2.isSelected()) 
            {
                 time_slot = hrbtn2.getText();
            }
            if(minbtn2.isSelected())
                    {
                       time_slot = minbtn2.getText(); 
                    }  
            pst.setString(2, time_slot);
            
//           String starting_time;
//           String htime = stimehour2.getValue().toString();
//           String mtime = stimemin2.getValue().toString();
//           String noon = noonselectbtn2.getSelectedItem().toString();
//      
//            starting_time = htime + ":" + mtime + "" + noon;
            pst.setString(3, stime3.getText());
             
           
             pst.executeUpdate();
             DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel(); 
             tblModel.setRowCount(0); 
             JOptionPane.showMessageDialog(null, "Updated successfully");
             con.close();
            
        }catch(Exception e){
            
             JOptionPane.showMessageDialog(null, e); 
        }
        
        DisplayTable();
    }//GEN-LAST:event_tslotupdatebtnActionPerformed

    private void tslotdelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tslotdelbtnActionPerformed
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmproject?zeroDateTimeBehavior=convertToNull", "root",""); 
           int row = jTable1.getSelectedRow();
           String value = (jTable1.getModel().getValueAt(row, 0).toString());
           String sql = "DELETE FROM time_slot WHERE id="+value;
           pst = con.prepareStatement(sql);
           pst.executeUpdate();
           DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel(); 
           tblModel.setRowCount(0); 
           
           JOptionPane.showMessageDialog(null, "Deleted"); 
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e); 
            
        }
        DisplayTable();
    }//GEN-LAST:event_tslotdelbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         // TODO add your handling code here:       
        int i =  jTable1.getSelectedRow();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        
        String selected_day = tblModel.getValueAt(i,1).toString();
            switch(selected_day){
                case "Monday":
                    dayselectbtn2.setSelectedIndex(0); 
                    break;
                case "Tuesday":
                    dayselectbtn2.setSelectedIndex(1); 
                    break;
                case "Wednesday":
                    dayselectbtn2.setSelectedIndex(2); 
                    break;
                case "Thursday":
                    dayselectbtn2.setSelectedIndex(3); 
                    break;
                case "Friday":
                    dayselectbtn2.setSelectedIndex(4); 
                    break;
                case "Sturday":
                    dayselectbtn2.setSelectedIndex(5); 
                    break;
                case "Sunday":
                    dayselectbtn2.setSelectedIndex(6); 
                    break;
            }
        
        String time_slot = tblModel.getValueAt(i,2).toString();
           if(time_slot.equals("hrbtn2")){
             hrbtn2.setSelected(true);
           }
           else{
              minbtn2.setSelected(true);
           }
         
        stime3.setText(tblModel.getValueAt(i, 3).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void timeslotsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeslotsave2ActionPerformed
        // TODO add your handling code here:
        
        dayselectbtn2.setSelectedItem("Monday");
        buttonGroup1.clearSelection();
        stime3.setText("");

//        try{
//
//            Class.forName("com.mysql.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmproject?zeroDateTimeBehavior=convertToNull", "root","");
//            pst = con.prepareStatement("insert into time_slot(selected_day,time_slot,starting_time)values(?,?,?)");
//
//            String selected_day;
//            selected_day = dayselectbtn2.getSelectedItem().toString();
//            pst.setString(1, selected_day);
//
//            String time_slot = null;
//            if(hourbtn.isSelected())
//            {
//                time_slot = hourbtn.getText();
//            }
//            if(minbtn.isSelected())
//            {
//                time_slot = minbtn.getText();
//            }
//            pst.setString(2, time_slot);
//
//            String starting_time;
//            String htime = stimemin2.getValue().toString();
//            String mtime = stimemin.getValue().toString();
//            String noon = noonselectbtn2.getSelectedItem().toString();
//
//            starting_time = htime + ":" + mtime + "" + noon;
//            pst.setString(3, starting_time);
//
//            pst.executeUpdate();
//            JOptionPane.showMessageDialog(null, "insert successful");
//            con.close();
//
//        }catch(Exception e){
//
//            JOptionPane.showMessageDialog(null, e);
//        }

    }//GEN-LAST:event_timeslotsave2ActionPerformed

    private void dayselectbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayselectbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayselectbtn2ActionPerformed

    private void hrbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrbtn2ActionPerformed

    private void minbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minbtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(des14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(des14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(des14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(des14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new des14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> dayselectbtn2;
    private javax.swing.JRadioButton hrbtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton minbtn2;
    private javax.swing.JLabel sday2;
    private javax.swing.JLabel stime2;
    private javax.swing.JTextField stime3;
    private javax.swing.JLabel sts2;
    private javax.swing.JButton timeslotsave2;
    private javax.swing.JButton tslotdelbtn;
    private javax.swing.JButton tslotupdatebtn;
    // End of variables declaration//GEN-END:variables

}
