/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpm.assi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinuka Wathsara
 */
public class Des9 extends javax.swing.JFrame {

    final String password = "";
    final String username = "root";
    final String DB_URL = "jdbc:mysql://localhost:3306/member2db";
    Connection con = null;
    PreparedStatement Insertps = null;

    /**
     * Creates new form Des9
     */
    public Des9() {
        initComponents();
        LectureName();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(DB_URL, username, password);

        } catch (SQLException ex) {
            Logger.getLogger(Des9.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Des9.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ArrayList<Lecturer> lecturerList() {

        ArrayList<Lecturer> lecturerList = new ArrayList<>();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(DB_URL, username, password);
            String query1 = "SELECT * FROM add_lecturer ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            Lecturer lecturer;

            while (rs.next()) {

                lecturer = new Lecturer(rs.getInt("EMP_ID"), rs.getString("LectureName"), rs.getString("Faculty"), rs.getString("Department"), rs.getString("Center"), rs.getString("Building"), rs.getString("Level"), rs.getString("Rank"));
                lecturerList.add(lecturer);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Des9.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Des9.class.getName()).log(Level.SEVERE, null, ex);
        }

        return lecturerList;
    }

    public void LectureName() {

        ArrayList<Lecturer> list = lecturerList();
        DefaultTableModel model = (DefaultTableModel) jTable1Lecturer.getModel();
        model.setRowCount(0);
        Object[] row = new Object[9];
        for (int i = 0; i < list.size(); i++) {
            row[0] = i + 1;
            row[1] = list.get(i).getLectureName();
            row[2] = list.get(i).getEMP_ID();
            row[3] = list.get(i).getFaculty();
            row[4] = list.get(i).getLevel();
            row[5] = list.get(i).getDepartment();
            row[6] = list.get(i).getCenter();
            row[7] = list.get(i).getBuilding();
            row[8] = list.get(i).getRank();
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Lecturer = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputLectureName = new javax.swing.JTextField();
        inputEMPID = new javax.swing.JTextField();
        inputRank = new javax.swing.JTextField();
        FacultyList = new javax.swing.JComboBox<>();
        DepartmentList = new javax.swing.JComboBox<>();
        Centerlist = new javax.swing.JComboBox<>();
        Buildinglist = new javax.swing.JComboBox<>();
        Levellist = new javax.swing.JComboBox<>();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage lecturers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(335, 335, 335)
                .addComponent(jLabel10)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTable1Lecturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Emp-ID", "Faculty", "Level", "Department", "Center", "Building", "Rank"
            }
        ));
        jTable1Lecturer.setFocusable(false);
        jTable1Lecturer.setRowHeight(25);
        jTable1Lecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1LecturerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Lecturer);

        btnClear.setBackground(new java.awt.Color(106, 116, 145));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel2.setText("Lecturer Name");

        jLabel3.setText("Employee ID");

        jLabel4.setText("Faculty");

        jLabel5.setText("Department");

        jLabel6.setText("Center");

        jLabel7.setText("Building");

        jLabel8.setText("Level");

        jLabel9.setText("Rank");

        FacultyList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Computing", "Business", "Engineering", "Human Resources" }));

        DepartmentList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "IT", "SE", "DS", "CS", "IM", "CSNE", "Civil", "Electronic Engineering", "Mechanical Engineering", "QS" }));

        Centerlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Malabe", "Matara", "Metro", "Kandy", "Kurunegala", "Jaffna" }));

        Buildinglist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "New Building", "D-Block", "Main Building" }));

        Levellist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Professor", "Assistant Professor", "Senior Lecturer(HG)", "Senior Lecturer", "Lecturer", "Assistant Lecturer" }));

        updatebtn.setBackground(new java.awt.Color(106, 116, 145));
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(106, 116, 145));
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputLectureName)
                            .addComponent(inputEMPID)
                            .addComponent(FacultyList, 0, 174, Short.MAX_VALUE)
                            .addComponent(DepartmentList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputRank)
                            .addComponent(Centerlist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buildinglist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Levellist, 0, 179, Short.MAX_VALUE))))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(inputLectureName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Centerlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(inputEMPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buildinglist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(FacultyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Levellist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(inputRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartmentList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try {
            int selectedRow = jTable1Lecturer.getSelectedRow();
            if (selectedRow != 1) {
                String sql = "delete from add_lecturer where EMP_ID='" + inputEMPID.getText() + "'";
                int result = con.prepareStatement(sql).executeUpdate();
                if (result == 1) {
                    //masg
                    JOptionPane.showMessageDialog(null, "Delete Successfully !!", "success", JOptionPane.INFORMATION_MESSAGE);
                } else {

                    //msg eorr
                    JOptionPane.showMessageDialog(null, "Inserted Not Successfully !!", "error", JOptionPane.ERROR_MESSAGE);
                }
                LectureName();
            }else{
                JOptionPane.showMessageDialog(null, "Select a row !!", "error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String eid = inputEMPID.getText();
        String lecturename = inputLectureName.getText();
        String faculty = FacultyList.getSelectedItem().toString();
        String department = DepartmentList.getSelectedItem().toString();
        String center = Centerlist.getSelectedItem().toString();
        String building = Buildinglist.getSelectedItem().toString();
        String level = Levellist.getSelectedItem().toString();
        String rank = inputRank.getText();

        if (!eid.isEmpty()) {

            if (!lecturename.isEmpty()) {

                if (!faculty.isEmpty()) {

                    if (!department.isEmpty()) {

                        if (!center.isEmpty()) {

                            if (!building.isEmpty()) {
                                if (!level.isEmpty()) {

                                    //tode
                                    int result;

                                    String sql = "INSERT INTO add_lecturer (EMP_ID ,LectureName,Faculty,Department,Center,Building,Level,Rank)VALUES(?,?,?,?,?,?,?,?)";

                                    try {
                                        Insertps = con.prepareStatement(sql);
                                    } catch (SQLException ex) {
                                        Logger.getLogger(Des9.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                    try {
                                        Insertps.setString(1, eid);
                                        Insertps.setString(2, lecturename);
                                        Insertps.setString(3, faculty);
                                        Insertps.setString(4, department);
                                        Insertps.setString(5, center);
                                        Insertps.setString(6, building);
                                        Insertps.setString(7, level);
                                        Insertps.setString(8, rank);

                                        result = Insertps.executeUpdate();
                                        if (result == 1) {

                                            //masg
                                            JOptionPane.showMessageDialog(null, "Inserted Successfully !!", "success", JOptionPane.INFORMATION_MESSAGE);
                                        } else {

                                            //msg eorr
                                            JOptionPane.showMessageDialog(null, "Inserted Not Successfully !!", "error", JOptionPane.ERROR_MESSAGE);
                                        }

                                    } catch (SQLException ex) {
                                        Logger.getLogger(Des9.class.getName()).log(Level.SEVERE, null, ex);
                                    }

                                } else {

                                    JOptionPane.showMessageDialog(null, " 1 ", "emp", JOptionPane.ERROR_MESSAGE);

                                }
                                JOptionPane.showMessageDialog(null, " 2 ", "lec", JOptionPane.ERROR_MESSAGE);

                            } else {

                                JOptionPane.showMessageDialog(null, " plz insert fac ", "faclty", JOptionPane.ERROR_MESSAGE);

                            }

                        } else {

                            JOptionPane.showMessageDialog(null, "3 ", "dip", JOptionPane.ERROR_MESSAGE);

                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "4 ", "cnter", JOptionPane.ERROR_MESSAGE);

                    }

                } else {
//                  msg
                    JOptionPane.showMessageDialog(null, " 5", "build", JOptionPane.ERROR_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(null, " 6 ", "level", JOptionPane.ERROR_MESSAGE);

            }

        } else {
//            JOptionPane.showMessageDialog(null, " plz insert rank ", "rank", JOptionPane.ERROR_MESSAGE);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        inputEMPID.setText("");
        inputLectureName.setText("");
        FacultyList.getSelectedItem().toString();
        DepartmentList.getSelectedItem().toString();
        Centerlist.getSelectedItem().toString();
        Buildinglist.getSelectedItem().toString();
        Levellist.getSelectedItem().toString();
        inputRank.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void jTable1LecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1LecturerMouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1Lecturer.getModel();
            int selectedRow = jTable1Lecturer.getSelectedRow();
            inputLectureName.setText(dtm.getValueAt(selectedRow, 1).toString());
            inputEMPID.setText(dtm.getValueAt(selectedRow, 2).toString());
            FacultyList.setSelectedItem(dtm.getValueAt(selectedRow, 3).toString());
            DepartmentList.setSelectedItem(dtm.getValueAt(selectedRow, 5).toString());
            Centerlist.setSelectedItem(dtm.getValueAt(selectedRow, 6).toString());
            Buildinglist.setSelectedItem(dtm.getValueAt(selectedRow, 7).toString());
            Levellist.setSelectedItem(dtm.getValueAt(selectedRow, 4).toString());
            inputRank.setText(dtm.getValueAt(selectedRow, 8).toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1LecturerMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try {
            int selectedRow = jTable1Lecturer.getSelectedRow();
            if (selectedRow != 1) {
                String sql = "update add_lecturer set LectureName='" + inputLectureName.getText() + "', Faculty='" + FacultyList.getSelectedItem().toString() + "', Department='" + DepartmentList.getSelectedItem().toString() + "', Center='" + Centerlist.getSelectedItem().toString() + "', Building='" + Buildinglist.getSelectedItem().toString() + "', Level='" + Levellist.getSelectedItem().toString() + "', Rank='" + inputRank.getText() + "' where EMP_ID='" + inputEMPID.getText() + "'";
                int result = con.prepareStatement(sql).executeUpdate();
                if (result == 1) {
                    //masg
                    JOptionPane.showMessageDialog(null, "Updated Successfully !!", "success", JOptionPane.INFORMATION_MESSAGE);
                } else {

                    //msg eorr
                    JOptionPane.showMessageDialog(null, "Inserted Not Successfully !!", "error", JOptionPane.ERROR_MESSAGE);
                }
                LectureName();
            }else{
                JOptionPane.showMessageDialog(null, "Select a row !!", "error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Des9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Des9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Des9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Des9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Des9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Buildinglist;
    private javax.swing.JComboBox<String> Centerlist;
    private javax.swing.JComboBox<String> DepartmentList;
    private javax.swing.JComboBox<String> FacultyList;
    private javax.swing.JComboBox<String> Levellist;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField inputEMPID;
    private javax.swing.JTextField inputLectureName;
    private javax.swing.JTextField inputRank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Lecturer;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
