/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpm.assi.member1;
import itpm.assi.util.connection;
import itpm.assi.common.homePg;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Vinuka Wathsara
 */
public class Des2 extends javax.swing.JFrame {
    Connection conn = null;

    /**
     * Creates new form Des2
     */
    public Des2() {
        initComponents();
        DisplayTable();
    }
    
       private void DisplayTable()
    {
        try{
        conn = connection.getConnection();
         
         String sql = "select * from student";
         
         PreparedStatement pstmt = conn.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery();
         
         mngstu.setModel(DbUtils.resultSetToTableModel(rs));
         
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hmBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mngstu = new javax.swing.JTable();
        clrstu = new javax.swing.JButton();
        updatestu = new javax.swing.JButton();
        delstu = new javax.swing.JButton();
        Gid = new javax.swing.JTextField();
        AYS = new javax.swing.JTextField();
        SGid = new javax.swing.JTextField();
        prg = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Gno = new javax.swing.JTextField();
        SGno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Student Groups ");

        hmBtn.setBackground(new java.awt.Color(106, 116, 145));
        hmBtn.setForeground(new java.awt.Color(255, 255, 255));
        hmBtn.setText("HOME");
        hmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hmBtn)
                .addGap(311, 311, 311)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hmBtn)))
                .addContainerGap())
        );

        mngstu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Academic Year Semester", "Programme", "Group No", "Group ID", "Sub Group No", "Sub Group ID"
            }
        ));
        mngstu.setFocusable(false);
        mngstu.setRowHeight(25);
        mngstu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mngstuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mngstu);

        clrstu.setBackground(new java.awt.Color(106, 116, 145));
        clrstu.setForeground(new java.awt.Color(255, 255, 255));
        clrstu.setText("Clear");
        clrstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrstuActionPerformed(evt);
            }
        });

        updatestu.setBackground(new java.awt.Color(106, 116, 145));
        updatestu.setForeground(new java.awt.Color(255, 255, 255));
        updatestu.setText("Update");
        updatestu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatestuActionPerformed(evt);
            }
        });

        delstu.setBackground(new java.awt.Color(106, 116, 145));
        delstu.setForeground(new java.awt.Color(255, 255, 255));
        delstu.setText("Delete");
        delstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delstuActionPerformed(evt);
            }
        });

        Gid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GidActionPerformed(evt);
            }
        });

        SGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SGidActionPerformed(evt);
            }
        });

        prg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programme", "CS", "DS", "ISE", "SE", "IT" }));

        jLabel2.setText("Group No");

        jLabel3.setText("Sub Group No");

        jLabel5.setText("Group ID");

        jLabel6.setText("Sub Group ID");

        jLabel7.setText("Academic Year Semester");

        jLabel8.setText("Programme");

        jLabel9.setText("ID");

        ID.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(clrstu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(updatestu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(delstu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SGno)
                                    .addComponent(Gid, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(SGid, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(Gno))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prg, 0, 164, Short.MAX_VALUE)
                                    .addComponent(AYS))))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clrstu, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updatestu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delstu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(AYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SGid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(prg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Gno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SGno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GidActionPerformed

    private void updatestuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatestuActionPerformed
            try{
                conn = connection.getConnection();
                
                String sql = "update student set academic_year_sem = ?, programme = ?, group_no = ?, subgroup_no = ?, group_id = ?, subgroup_id = ? where id = ?";
            
                PreparedStatement pstmt = conn.prepareStatement(sql);
                
                pstmt.setString(1,AYS.getText());
                
                String programme;
                programme = prg.getSelectedItem().toString();
                pstmt.setString(2, programme);
                
                pstmt.setInt(3,Integer.parseInt(Gno.getText()));
               
                pstmt.setInt(4,Integer.parseInt(SGno.getText()));
                
                pstmt.setString(5,Gid.getText());;
                
                pstmt.setString(6,SGid.getText());
                
                pstmt.setString(7,ID.getText());
                
                
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Updated Successfully!!");
                DisplayTable();
                conn.close();
            
    
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
            


        // TODO add your handling code here:
    }//GEN-LAST:event_updatestuActionPerformed

    private void clrstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrstuActionPerformed
            //ClearFields();

            ClearFields();
        // TODO add your handling code here:
    }//GEN-LAST:event_clrstuActionPerformed

    private void SGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SGidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SGidActionPerformed

    private void mngstuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mngstuMouseClicked
        // TODO add your handling code here:
        
        
        ID.setText( mngstu.getValueAt(mngstu.getSelectedRow(), 0).toString());
        Gid.setText( mngstu.getValueAt(mngstu.getSelectedRow(), 5).toString());
        SGid.setText( mngstu.getValueAt(mngstu.getSelectedRow(), 6).toString());
        Gno.setText( mngstu.getValueAt(mngstu.getSelectedRow(), 3).toString());
        SGno.setText( mngstu.getValueAt(mngstu.getSelectedRow(), 4).toString());
        AYS.setText( mngstu.getValueAt(mngstu.getSelectedRow(), 1).toString());
       
        
       String comboVal=mngstu.getValueAt(mngstu.getSelectedRow(), 2).toString();
        if(comboVal.equalsIgnoreCase("cs")){
            prg.setSelectedIndex(1);
        } else if (comboVal.equalsIgnoreCase("ds")) {
            prg.setSelectedIndex(2);
        } else if (comboVal.equalsIgnoreCase("ise")) {
            prg.setSelectedIndex(3);
        } else if (comboVal.equalsIgnoreCase("se")) {
            prg.setSelectedIndex(4);
        }  else if (comboVal.equalsIgnoreCase("it")) {
            prg.setSelectedIndex(5);
        } else {
            prg.setSelectedIndex(0);
        }
    }//GEN-LAST:event_mngstuMouseClicked

    private void delstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delstuActionPerformed
            try{
                conn = connection.getConnection();
                
                String sql = "delete from student where id = ?";
            
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(ID.getText()));
               
                int result = pstmt.executeUpdate();
                if( result > 0 ){
         
                        JOptionPane.showMessageDialog(null, "Record Deleted Successfully!!!");
                        ClearFields();
                    }
                    else{
                            JOptionPane.showMessageDialog(null, "Record Could Not Be Found");
          
                }
                    DisplayTable();
             conn.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
            }
            
            

        // TODO add your handling code here:
    }//GEN-LAST:event_delstuActionPerformed

    private void hmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmBtnActionPerformed
            new homePg().setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_hmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Des2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Des2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Des2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Des2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Des2().setVisible(true);
            }
        });
    }
    
    private void ClearFields(){
        
        ID.setText("");
        AYS.setText("");
        prg.setSelectedIndex(0);
        Gno.setText("");
        SGno.setText("");
        Gid.setText("");
        SGid.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AYS;
    private javax.swing.JTextField Gid;
    private javax.swing.JTextField Gno;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField SGid;
    private javax.swing.JTextField SGno;
    private javax.swing.JButton clrstu;
    private javax.swing.JButton delstu;
    private javax.swing.JButton hmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mngstu;
    private javax.swing.JComboBox<String> prg;
    private javax.swing.JButton updatestu;
    // End of variables declaration//GEN-END:variables
}
