package itpm.assi.member3;

import itpm.assi.util.connection;
import itpm.assi.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author yasho
 */
public class PreffSession extends javax.swing.JFrame {
    Connection conn = null;        //create the connection object con
    PreparedStatement pst; // create the PreparedStatement object pst
    ResultSet rs;          // create the ResultSet object rs
    Statement stmt;        // create the Statement object stmt
    

    public PreffSession() {
        initComponents();
        loadsessions();
        loadlocation();
        DisplayTable();
    }
    
    private void DisplayTable(){
        try{            
            conn = connection.getConnection();
            
            String sql = "select * from preff_session"; 
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery(sql);
            
            jTablepresess.setModel(DbUtils.resultSetToTableModel(rs));
     
            conn.close();
      
        }catch(Exception e){
            
           JOptionPane.showMessageDialog(null, e); 
        
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftime5 = new javax.swing.JTextField();
        selsess = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selday5 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        selroom = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablepresess = new javax.swing.JTable();
        cleps = new javax.swing.JButton();
        delps = new javax.swing.JButton();
        updateps = new javax.swing.JButton();
        saveps = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Preffered Sessions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(354, 354, 354))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        ftime5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftime5ActionPerformed(evt);
            }
        });

        selsess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selsessActionPerformed(evt);
            }
        });

        jLabel2.setText("Session");

        jLabel3.setText("Date");

        selday5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        selday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selday5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Time");

        selroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selroomActionPerformed(evt);
            }
        });

        jLabel7.setText("Room");

        jTablepresess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Session", "Room", "Date", "Time"
            }
        ));
        jTablepresess.setFocusable(false);
        jTablepresess.setRowHeight(25);
        jTablepresess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablepresessMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablepresess);

        cleps.setBackground(new java.awt.Color(255, 255, 153));
        cleps.setText("CLEAR ALL");
        cleps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clepsActionPerformed(evt);
            }
        });

        delps.setBackground(new java.awt.Color(204, 255, 204));
        delps.setText("DELETE");
        delps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delpsActionPerformed(evt);
            }
        });

        updateps.setBackground(new java.awt.Color(255, 204, 204));
        updateps.setText("UPDATE");
        updateps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepsActionPerformed(evt);
            }
        });

        saveps.setBackground(new java.awt.Color(204, 204, 255));
        saveps.setText("SAVE");
        saveps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepsActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Msi 9RDS\\Desktop\\ITPM-master\\icons\\back_to_26px.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Msi 9RDS\\Desktop\\ITPM-master\\icons\\home_24px.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(198, 198, 198)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selday5, 0, 227, Short.MAX_VALUE)
                                    .addComponent(selsess, 0, 227, Short.MAX_VALUE)
                                    .addComponent(selroom, 0, 227, Short.MAX_VALUE)
                                    .addComponent(ftime5)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(saveps, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateps, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delps, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cleps, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 341, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selsess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(selday5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftime5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveps)
                    .addComponent(updateps)
                    .addComponent(delps)
                    .addComponent(cleps))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftime5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftime5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftime5ActionPerformed

    private void selsessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selsessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selsessActionPerformed

    private void selday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selday5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selday5ActionPerformed

    private void selroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selroomActionPerformed

    private void jTablepresessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablepresessMouseClicked
        // TODO add your handling code here:
        selsess.setSelectedItem(jTablepresess.getValueAt(jTablepresess.getSelectedRow(), 1).toString());
        selroom.setSelectedItem(jTablepresess.getValueAt(jTablepresess.getSelectedRow(), 2).toString());
        selday5.setSelectedItem(jTablepresess.getValueAt(jTablepresess.getSelectedRow(), 3).toString());
        ftime5.setText(jTablepresess.getValueAt(jTablepresess.getSelectedRow(), 4).toString());
       
    }//GEN-LAST:event_jTablepresessMouseClicked

    private void clepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clepsActionPerformed
        // TODO add your handling code here:
         selsess.setSelectedItem(null);
        selroom.setSelectedItem(null);
        selday5.setSelectedItem(null);
        ftime5.setText("");
    }//GEN-LAST:event_clepsActionPerformed

    private void delpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delpsActionPerformed
        // TODO add your handling code here:
        try{
           conn = connection.getConnection();
           
           int row = jTablepresess.getSelectedRow();
           String value = (jTablepresess.getModel().getValueAt(row, 0).toString());
           String sql = "DELETE FROM preff_session WHERE id="+value;
           pst = conn.prepareStatement(sql);
           pst.executeUpdate();
           DefaultTableModel tblModel = (DefaultTableModel)jTablepresess.getModel(); 
           tblModel.setRowCount(0); 
           
           JOptionPane.showMessageDialog(null, "Deleted"); 
        
        conn.close();
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e); 
            
        }
        DisplayTable();
    }//GEN-LAST:event_delpsActionPerformed

    private void updatepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepsActionPerformed
        // TODO add your handling code here:
        try{
             conn = connection.getConnection();
             
             int row = jTablepresess.getSelectedRow();
             String value = (jTablepresess.getModel().getValueAt(row, 0).toString());
             String sql = "UPDATE preff_session SET session=?, tag=?, date=?, time=? WHERE id ="+value;
             pst = conn.prepareStatement(sql);
             
            String session;
            session = selsess.getSelectedItem().toString();
            pst.setString(1, session);
            
            String room;
            room = selroom.getSelectedItem().toString();
            pst.setString(2, room);
            
            String date;
            date = selday5.getSelectedItem().toString();
            pst.setString(3, date);
            
            pst.setString(4, ftime5.getText());
            
              pst.executeUpdate();
             DefaultTableModel tblModel = (DefaultTableModel)jTablepresess.getModel(); 
             tblModel.setRowCount(0); 
             JOptionPane.showMessageDialog(null, "Updated successfully");
             conn.close();
       
        }catch(Exception e){
            
             JOptionPane.showMessageDialog(null, e); 
        }
        
        DisplayTable();  
            
             
    }//GEN-LAST:event_updatepsActionPerformed

    private void savepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepsActionPerformed
        // TODO add your handling code here:
        try{
            conn = connection.getConnection();
            pst = conn.prepareStatement("insert into preff_session(session,tag,date,time)values(?,?,?,?)");
            
            String session;
            session = selsess.getSelectedItem().toString();
            pst.setString(1, session);
            
            String room;
            room = selroom.getSelectedItem().toString();
            pst.setString(2, room);
            
            String date;
            date = selday5.getSelectedItem().toString();
            pst.setString(3, date);
            
            pst.setString(4, ftime5.getText());
         
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "inserted successfully");
           conn.close();
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
          }
        DisplayTable();
    }//GEN-LAST:event_savepsActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreffSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreffSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreffSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreffSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreffSession().setVisible(true);
            }
        });
    }
    public void loadsessions(){
          try{
             conn = connection.getConnection();
             
             String sql = "Select Subjectname from add_subject";
             pst = conn.prepareStatement(sql);
             
             rs = pst.executeQuery();
             
             while (rs.next()){
                 String name = rs.getString("Subjectname");
                 selsess.addItem(name);
                }
             conn.close();
             
        }catch(Exception e){
            
          JOptionPane.showMessageDialog(null, e);
        }   
    }
     public void loadlocation(){
          try{
             conn = connection.getConnection();
             
             String sql = "Select roomName from addlocation";
             pst = conn.prepareStatement(sql);
             
             rs = pst.executeQuery();
             
             while (rs.next()){
                 String name2 = rs.getString("roomName");
                 selroom.addItem(name2);
                }
             conn.close();
             
        }catch(Exception e){
            
          JOptionPane.showMessageDialog(null, e);
        }   
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleps;
    private javax.swing.JButton delps;
    private javax.swing.JTextField ftime5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablepresess;
    private javax.swing.JButton saveps;
    private javax.swing.JComboBox selday5;
    private javax.swing.JComboBox selroom;
    private javax.swing.JComboBox selsess;
    private javax.swing.JButton updateps;
    // End of variables declaration//GEN-END:variables
}
